[workspace]
name = "bm_pirna"
description = "The purpose of this project is to analyze genes related to piRNA synthesis that were identified by screening a whole-genome library of the silkworm, with the aim of elucidating a comprehensive view of piRNA synthesis in the silkworm."
version = "0.1.0"
channels = ["conda-forge", "bioconda"]
platforms = ['linux-64', 'osx-64', 'osx-arm64', 'win-64']

[dependencies]
python = "~=3.10.0"
loguru = "*"
ruff = "*"
tqdm = "*"
typer = "*"
pip = "*"
ipykernel = ">=7.1.0,<8"

[pypi-dependencies]
python-dotenv = "*"
bm_pirna = { path = ".", editable = true }
